### PR TITLE
Adding validation capabilities to the napalm-base (#100)

### PR DESCRIPTION
**Pull request by dbarrosop**
Do NOT merge, this is mostly to discuss features and collaborate.

TODO:

1. A CLI tool.
2. Ansible module for assertions (TBD after this is actually released).

Quick how to:

The idea of this feature is to use napalm to build compliance reports. Given a validation file like this:

https://github.com/napalm-automation/napalm-base/blob/validate/test/unit/validate/mocked_data/simple/validate.yml

Napalm is going to retrieve data and configuration from the live device and verify it against the file. Then, in your code you could do:

```
with driver(hostname, username, ...) as device:
    errors = device.compliance_errors("/path/to/compliance.yml")
    if not errors:
          print("We are compliant!!!)
    else:
          print("We are not:\n{}".format(errors))
```

And get things like:

```
# if the device is compliant
{}

# If the device has some live data that doesn't comply
{'get_arp_table': {'not_matched': [
                    "Expected but not found: {'interface': 'Ethernet3/1', 'ip': '192.0.2.3'}"]},
 'get_bgp_neighbors': {'default': ['Expected key but not found.']}}

# Or even configuration
{'Expected but not found in running config': ['logging server 10.0.0.1']}
```

### CODE REVIEW

**Comment by dbarrosop** [comment]
@GGabriele I have done some "minor" changes:

1. No need of passing a list of getters to run anymore.
2. Instead of returning `true` if everything is fine or a dict with the errors, we always return a dict with the errors. If it's empty, it means everything is fine.
3. I renamed the method to `compliance_errors` as it's more readable given the return value of the function.

Thoughts?

**Comment by GGabriele** [comment]
This looks good to me, great work.

Regarding the CLI tool, where should we push it? From a CLI perspective, how do you want this to look?

**Comment by dbarrosop** [comment]
@GGabriele there are some here already: https://github.com/napalm-automation/napalm-base/tree/develop/napalm_base/clitools

**Comment by GGabriele** [comment]
@dbarrosop I can help with that when you'll merge this if you want

**Comment by dbarrosop** [comment]
Guys, I am going to merge this. A couple of notes:

1. The configuration validation part is out for the moment. I want to see if we can integrate it somehow with nelkit
2. Doc is published here: https://napalm.readthedocs.io/en/latest/validate/index.html

**Comment by dbarrosop** [comment]
@GGabriele feel free to take a look to the CLI, let me know if you need help : )

**Pull request merged**
