### PR TITLE
Test multiple identical remarks (for #277)

### PR DESCRIPTION
**Pull request by ogenstad**
Another test for #277 which uses multiple identical remarks. Don't know how common this would be, only thinking about scenarios where the differ might be struggling.

### CODE REVIEW

**Comment by dbarrosop** [comment]
Will be merged via #277

**Comment by dbarrosop** [comment]
Oh, I see what you did here. Goddamn you, you broke it!!!

I will think about it but I'd say it's fine if the diff shows only:

```
  ip access-list extended TEST-ACL
+   remark # DENY
+   deny  ip any any
```

As it's the case. The solution might be too ugly for little gain as this is mostly aesthetics, the unreported command actually doesn't give you any useful information and I am sure nobody would miss it :P

Anyway, will scratch my head around this for a while...

**Comment by ogenstad** [comment]
Mission accomplished ;)

But yeah, I agree with you. Don't know if there's a real problem here, just a strange thing which might pop up sometime. Can't think of any other scenario which would look like this one.

**Comment by dbarrosop** [comment]
Closing this one for the time being.

**Pull request closed without merging**
