### PR TITLE
Enhance helpers

### PR DESCRIPTION
**Pull request by mirceaulinic**
@dbarrosop @ktbyers please review

### CODE REVIEW

**Comment by inetuid** [comment]
What would be involved in changing mac() and ip() to return a class so that they could be used in the test models? At present they return unicode so it's difficult to tell if a driver used them or not.

**Comment by mirceaulinic** [comment]
AFAIK there's no driver using them yet. Their only purpose is to return a standard representation across all drivers as currently they depend on the vendor.

**Comment by inetuid** [comment]
I don't think I was clear on my intent. Currently napalm_base/test/models.py has something like:

```
arp_table = {
    'interface' : unicode,
    'mac'       : unicode,
    'ip'        : unicode,
    'age'       : float
}
```

I was wondering whether it could be changed to something like:

```
arp_table = {
    'interface' : unicode,
    'mac'       : mac_class,
    'ip'        : ip_class,
    'age'       : float
}
```

At present I don't think this is possible as mac() and ip() return unicode() so would pass current tests.

**Comment by mirceaulinic** [comment]
I see what you mean and does make sense. But if we are doing this right now, all the tests will fail :) The only way we can avoid this to happen would be to synchronise and update all of them at once.

**Comment by dbarrosop** [comment]
I think what you are talking would be easier to do if we would have on out tests something like

```
assert is_valid_mac(result['mac_address'])
```

We can probably figure something out for the future but I would leave existing methods as they are.

**Pull request merged**
