### PR TITLE
find_txt and convert functions in helpers

### PR DESCRIPTION
**Pull request by mirceaulinic**
I find both functions very useful and needed more and more. In order to not define them again and again in each driver class, I think we should include them in the helpers module (actually that was their purpose) and use wherever needed.

### CODE REVIEW

**Comment by mirceaulinic** [comment]
After merging this PR, I will update all drivers to use the functions from napalm_base.helpers, instead of the local defined static methods.

**Comment by dbarrosop** [comment]
Could we have some unittests? If drivers are going to rely on these we should have tests. Other than that it's a brilliant idea : )

**Comment by mirceaulinic** [comment]
Sure, I will find some time next week to write the tests and make some
cleanups in the code of the drivers i work on mostly.

Le sam. 30 avr. 2016 19:47, David Barroso <notifications@github.com> a
écrit :

**Comment by mirceaulinic** [comment]
@dbarrosop added some tests too.

**Comment by dbarrosop** [comment]
💯

**Pull request merged**
