### PR TITLE
New helper: ip

### PR DESCRIPTION
**Pull request by mirceaulinic**
Comes together with ```mac``` (https://github.com/napalm-automation/napalm-base/pull/54) to prepare the eggs for the upcoming cleanup/hackathon.

### CODE REVIEW

**Comment by mirceaulinic** [comment]
For consistency I would recommend using it whenever retrieving an IP address value from the devices. I noticed that not even Juniper is consistent, sometimes providing IPv6 addresses without zeroes-grouping.

**Comment by dbarrosop** [comment]
Yay! We broke this one... can you rebase?

**Comment by mirceaulinic** [comment]
All right, rebased

**Comment by dbarrosop** [comment]
Thx! Retriggering other tests.

**Comment by mirceaulinic** [comment]
Don't hurry - just noticed I forgot to provide mock data in all my recent PRs, so they will fail 😞

**Pull request merged**
