### PR TITLE
Implements #206

### PR DESCRIPTION
**Pull request by narJH27**
Implements #206

### CODE REVIEW

**Comment by narJH27** [comment]
@dbarrosop @mirceaulinic Good To merge?

**Comment by mirceaulinic** [comment]
Hi @narJH27 - we either need to add this to #206, either add the documentation details from #206 here.
Anyway, as explained in #206, we cannot merge API changes before implementing the changes in the affected drivers.

**Comment by mirceaulinic** [comment]
For more info see: https://github.com/napalm-automation/napalm-base/pull/206#issuecomment-279185431 - there are quite a few drivers affected by this change.

**Comment by narJH27** [comment]
@mirceaulinic I understand. I will try to get to the other drivers when I can, but I do not have access to a lot of the vendor boxes. So if someone could help out, it would be great!

**Comment by mirceaulinic** [comment]
Hi @narJH27 - I have moved your commit into https://github.com/napalm-automation/napalm-base/pull/206 as that is the issue tracking the API change. Thanks!

**Pull request closed without merging**
