### PR TITLE
pylama cleanup of napalm-base

### PR DESCRIPTION
**Pull request by ktbyers**
This should be all pylama cleanup. Please test, however.

### CODE REVIEW

**Comment by ktbyers** [comment]
Also should make sure I didn't break any of the auto-generated documentation (built from the docstrings).

**Comment by dbarrosop** [comment]
This is great! Will do some tests : )

Could you add `pylama .` at the end of the `script` section in the file `.travis.yml`?

**Comment by ktbyers** [comment]
@dbarrosop It is not done, but I put a dent in it...

Note, I am ignoring all the openconfig/pyangbind pylint warnings.

**Comment by dbarrosop** [comment]
Ok, I will merge it right after the new testing framework. I will try to make it pass then : )

**Pull request merged**
